// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeLibrary.Infrastructure.Persistence;

#nullable disable

namespace RecipeLibrary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20260718134248_AddPendingConversionSuggestionUniqueness")]
    partial class AddPendingConversionSuggestionUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.CanonicalIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CatalogKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UserGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CatalogKey")
                        .IsUnique()
                        .HasFilter("[CatalogKey] IS NOT NULL");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ConversionSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ConversionSources", (string)null);
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Preparation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientMatchLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("MatchedIngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedInput")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MatchedIngredientId");

                    b.ToTable("IngredientMatchLogs", (string)null);
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientTag", b =>
                {
                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IngredientId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("IngredientTags", (string)null);
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId", "LanguageCode")
                        .IsUnique();

                    b.HasIndex("LanguageCode", "NormalizedDisplayName");

                    b.ToTable("IngredientTranslations", (string)null);
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientTranslationAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("IngredientTranslationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientTranslationId");

                    b.HasIndex("NormalizedAlias");

                    b.ToTable("IngredientTranslationAliases", (string)null);
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientUnitConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountFrom")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("AmountTo")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("CanonicalIngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversionSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FromUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ToUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ConversionSourceId");

                    b.HasIndex("CanonicalIngredientId", "FromUnit", "ToUnit", "ConversionSourceId")
                        .IsUnique();

                    b.ToTable("IngredientUnitConversions", (string)null);
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientUnitConversionSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountFrom")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("AmountTo")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("CanonicalIngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FromUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("IngredientDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ToUnit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalIngredientId", "FromUnit", "ToUnit")
                        .IsUnique()
                        .HasFilter("[Status] = N'Pending' AND [CanonicalIngredientId] IS NOT NULL");

                    b.HasIndex("IngredientDisplayName", "FromUnit", "ToUnit")
                        .IsUnique()
                        .HasFilter("[Status] = N'Pending' AND [CanonicalIngredientId] IS NULL");

                    b.HasIndex("CanonicalIngredientId", "FromUnit", "ToUnit", "Status");

                    b.ToTable("IngredientUnitConversionSuggestions", (string)null);
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.InstructionStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("InstructionSteps");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.PantryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CanonicalIngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalIngredientId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CookingMinutes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PreparationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StoreOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "StoreOrder")
                        .IsUnique();

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ShoppingListGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ShoppingListGroups");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CanonicalIngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Preparation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ShoppingListItemSource", b =>
                {
                    b.Property<Guid>("ShoppingListItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecipeTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ShoppingListItemId", "RecipeId");

                    b.ToTable("ShoppingListItemSources");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.CanonicalIngredient", "IngredientDefinition")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RecipeLibrary.Domain.Entities.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientDefinition");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientMatchLog", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.CanonicalIngredient", "MatchedIngredient")
                        .WithMany()
                        .HasForeignKey("MatchedIngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MatchedIngredient");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientTag", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.CanonicalIngredient", "Ingredient")
                        .WithMany("IngredientTags")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeLibrary.Domain.Entities.Tag", "Tag")
                        .WithMany("IngredientTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientTranslation", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.CanonicalIngredient", "Ingredient")
                        .WithMany("Translations")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientTranslationAlias", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.IngredientTranslation", "Translation")
                        .WithMany("Aliases")
                        .HasForeignKey("IngredientTranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Translation");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientUnitConversion", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.CanonicalIngredient", "CanonicalIngredient")
                        .WithMany()
                        .HasForeignKey("CanonicalIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeLibrary.Domain.Entities.ConversionSource", "ConversionSource")
                        .WithMany()
                        .HasForeignKey("ConversionSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalIngredient");

                    b.Navigation("ConversionSource");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientUnitConversionSuggestion", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.CanonicalIngredient", "CanonicalIngredient")
                        .WithMany()
                        .HasForeignKey("CanonicalIngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanonicalIngredient");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.InstructionStep", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.Recipe", null)
                        .WithMany("InstructionSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.PantryItem", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.CanonicalIngredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("CanonicalIngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ShoppingList", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.ShoppingListGroup", "Group")
                        .WithMany("Lists")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ShoppingListItem", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ShoppingListItemSource", b =>
                {
                    b.HasOne("RecipeLibrary.Domain.Entities.ShoppingListItem", "Item")
                        .WithMany("Sources")
                        .HasForeignKey("ShoppingListItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.CanonicalIngredient", b =>
                {
                    b.Navigation("IngredientTags");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.IngredientTranslation", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("InstructionSteps");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ShoppingListGroup", b =>
                {
                    b.Navigation("Lists");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.ShoppingListItem", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("RecipeLibrary.Domain.Entities.Tag", b =>
                {
                    b.Navigation("IngredientTags");
                });
#pragma warning restore 612, 618
        }
    }
}
